preserve_hierarchy: true
export_languages:
  - en
  - de
files:
  - source: /packages/i18n/messages/nl.json
    translation: /packages/i18n/messages/%two_letters_code%.json
    skip_untranslated_strings: true
