export const MAX_EVENT_TITLE_LENGTH = 200;
export const MAX_EVENT_DESCRIPTION_LENGTH = 2000;
export const MAX_EVENT_LOCATION_LENGTH = 300;
export const MAX_EVENT_NOTES_LENGTH = 2000;
export const MAX_DECLINE_REASON_LENGTH = 500;
export const MAX_INVITATIONS_PER_EVENT = 20;
export const REMINDER_HOURS_BEFORE_EVENT = 24;
