import { defineEnum } from "./utils/define-enum";

// ─── Cities (proper nouns — stay as-is) ───────────────────────────────────

export const City = defineEnum([
  "amsterdam",
  "rotterdam",
  "den_haag",
  "utrecht",
  "groningen",
  "eindhoven",
  "tilburg",
  "nijmegen",
  "enschede",
  "arnhem",
  "leiden",
  "maastricht",
  "delft",
  "breda",
  "leeuwarden",
  "zwolle",
  "den_bosch",
  "haarlem",
  "wageningen",
  "middelburg",
  "vlissingen",
  "deventer",
  "apeldoorn",
  "amersfoort",
  "almere",
  "dordrecht",
  "heerlen",
  "sittard",
  "venlo",
  "helmond",
  "zoetermeer",
  "amstelveen",
  "alkmaar",
  "hilversum",
  "lelystad",
  "purmerend",
  "hengelo",
  "zaandam",
  "schiedam",
  "hoofddorp",
  "ede",
  "gouda",
  "hoorn",
  "vlaardingen",
  "alphen_aan_den_rijn",
  "spijkenisse",
  "almelo",
  "assen",
  "veenendaal",
  "capelle_aan_den_ijssel",
  "roosendaal",
  "nieuwegein",
  "heerhugowaard",
  "oss",
  "emmen",
  "rijswijk",
  "zeist",
  "bergen_op_zoom",
  "dronten",
  "terschelling",
] as const);
export type City = (typeof City.values)[number];
