import { defineEnum } from "./utils/define-enum";

// ─── Verenigingen (proper nouns — stay as-is) ─────────────────────────────

export const Vereniging = defineEnum([
  // Alkmaar
  "omnivas",
  // Almere
  "endzjin_sveia",
  "sv_bazinga",
  // Amsterdam
  "asc_avsv",
  "asv_gay",
  "aegee_amsterdam",
  "sib_amsterdam",
  "sa_comitas",
  "sv_cyclades",
  "odd_selene",
  "derm",
  "lanx",
  "sv_liber",
  "svaa_nonomes",
  "particolarte",
  "ssra",
  "unitas_sa",
  // Arnhem
  "arboricultura",
  "sv_creas",
  "sv_campuscafe_lokaal_99",
  "quercus",
  "trolleystam",
  // Breda
  "sv_maximus",
  "sv_phileas_fogg",
  "sv_virgo",
  // Delft
  "aegee_delft",
  "aldgillis",
  "delftsch_studenten_corps",
  "delftsche_studenten_bond",
  "delftsche_zwervers",
  "dsv_nieuwe_delft",
  "dsv_sint_jansbrug",
  "outsite",
  "ksv_sanctus_virgilius",
  "mv_wolbodo",
  "moeder_delftsche",
  "ojv_de_koornbeurs",
  "sv_hezarfen",
  "sv_nova",
  "uknighted",
  "vsstd",
  // Deventer
  "nescio",
  "pro_deo",
  // Dronten
  "usra",
  // Eindhoven
  "aegee_eindhoven",
  "atmos",
  "br_beurs",
  "cosmos",
  "compass",
  "esv_demos",
  "estv_doppio",
  "eindhovens_studenten_corps",
  "jces_kinjin",
  "sa_salaam",
  "ssre",
  "tuna_ciudad_de_luz",
  "ledstam",
  // Enschede
  "audentis_et_virtutis",
  "asv_taste",
  "aegee_enschede",
  "csv_alpha_enschede",
  "radix",
  // Den Haag
  "hsv",
  "intac",
  "la_confrerie",
  // Groningen
  "aegee_groningen",
  "albertus_magnus",
  "ffj_bernlef",
  "cavv",
  "cleopatra",
  "asv_dizkartes",
  "flanor",
  "csg_gica",
  "ganymedes",
  "gsv_groningen",
  "csv_ichthus_groningen",
  "martinistam",
  "unitas_sg",
  "sib_groningen",
  "vindicat",
  // Haarlem
  "carpe_noctem",
  "haerlems_studenten_gildt",
  // Heerlen
  "volupia",
  "woord_en_daad",
  // Den Bosch
  "animoso",
  "gremio_unio",
  // Leeuwarden
  "io_vivat",
  "osiris",
  "asvl_sempiternus",
  "wolweze",
  "luwt_stam",
  // Leiden
  "augustinus",
  "catena",
  "minerva",
  "quintus",
  "ssr_leiden",
  "aegee_leiden",
  "dac",
  "sib_leiden",
  "het_duivelsei",
  "asv_prometheus",
  "sleutelstam",
  "gnsv_leiden",
  // Maastricht
  "amphitryon",
  "circumflex",
  "sv_koko",
  "tragos",
  // Nijmegen
  "aegee_nijmegen",
  "nsv_carolus_magnus",
  "asv_karpe_noktem",
  "noviomagustam",
  "nsba",
  "nsv_ovum_novum",
  "sv_sturad",
  "vsa_nijmegen",
  "gnsv_nijmegen",
  // Rotterdam
  "rsc_rvsv",
  "rsv_sanctus_laurentius",
  "ssr_rotterdam",
  "rsg",
  "nsr",
  "vgsr",
  // Terschelling
  "wbs",
  // Tilburg
  "tsv_plato",
  "sint_olof",
  "totus",
  // Utrecht
  "biton",
  "sib_utrecht",
  "ssr_nu",
  "uhsv_anteros",
  "umtc",
  "unitas_srt",
  "utrechtsch_studenten_corps",
  "uvsv_nvvsu",
  "veritas",
  "ufo_stam",
  "gnsv_utrecht",
  // Vlissingen
  "aqua_ad_vinum",
  "marum_bibio",
  // Wageningen
  "brabants_studenten_gilde",
  "wsv_ceres",
  "franciscus_xaverius",
  "t_noaberschop",
  "dlv_nji_sri",
  "ssr_w",
  "unitas_wageningen",
  "wsg_paragon",
  "yggdrasilstam",
  // Zaandam
  "zsv",
  // Zwolle
  "gumbo_millennium",
  "oikos_nomos",
  "zhtc",
  // Fallback
  "other",
] as const);
export type Vereniging = (typeof Vereniging.values)[number];
