CREATE OR REPLACE VIEW "conversation_members_rls" AS (select "conversation_id", "user_id" from "conversation_members");--> statement-breakpoint
CREATE OR REPLACE VIEW "room_members_rls" AS (select "room_id", "user_id", "role" from "housemates");--> statement-breakpoint
ALTER POLICY "housemates_select" ON "housemates" TO "authenticated" USING (exists(select 1 from room_members_rls where room_members_rls.room_id = "housemates"."room_id" and room_members_rls.user_id = (select auth.user_id())));--> statement-breakpoint
ALTER POLICY "applications_select" ON "applications" TO "authenticated" USING ((select auth.user_id()) = "applications"."user_id" or exists(select 1 from room_members_rls where room_members_rls.room_id = "applications"."room_id" and room_members_rls.user_id = (select auth.user_id())));--> statement-breakpoint
ALTER POLICY "applications_update" ON "applications" TO "authenticated" USING ((select auth.user_id()) = "applications"."user_id" or exists(select 1 from room_members_rls where room_members_rls.room_id = "applications"."room_id" and room_members_rls.user_id = (select auth.user_id()) and room_members_rls.role in ('owner', 'admin')));--> statement-breakpoint
ALTER POLICY "reviews_select" ON "reviews" TO "authenticated" USING (exists(select 1 from room_members_rls where room_members_rls.room_id = "reviews"."room_id" and room_members_rls.user_id = (select auth.user_id())));--> statement-breakpoint
ALTER POLICY "reviews_insert" ON "reviews" TO "authenticated" WITH CHECK ((select auth.user_id() = "reviews"."reviewer_id") and exists(select 1 from room_members_rls where room_members_rls.room_id = "reviews"."room_id" and room_members_rls.user_id = (select auth.user_id())));--> statement-breakpoint
ALTER POLICY "hospi_events_select" ON "hospi_events" TO "authenticated" USING (exists(select 1 from room_members_rls where room_members_rls.room_id = "hospi_events"."room_id" and room_members_rls.user_id = (select auth.user_id())));--> statement-breakpoint
ALTER POLICY "conversation_members_select" ON "conversation_members" TO "authenticated" USING (exists(select 1 from conversation_members_rls where conversation_members_rls.conversation_id = "conversation_members"."conversation_id" and conversation_members_rls.user_id = (select auth.user_id())));--> statement-breakpoint
ALTER POLICY "conversation_members_insert" ON "conversation_members" TO "authenticated" WITH CHECK ("conversation_members"."user_id" = (select auth.user_id()) or exists(select 1 from conversation_members_rls where conversation_members_rls.conversation_id = "conversation_members"."conversation_id" and conversation_members_rls.user_id = (select auth.user_id())));--> statement-breakpoint
ALTER POLICY "conversations_select" ON "conversations" TO "authenticated" USING (exists(select 1 from conversation_members_rls where conversation_members_rls.conversation_id = "conversations"."id" and conversation_members_rls.user_id = (select auth.user_id())));--> statement-breakpoint
ALTER POLICY "messages_select" ON "messages" TO "authenticated" USING (exists(select 1 from conversation_members_rls where conversation_members_rls.conversation_id = "messages"."conversation_id" and conversation_members_rls.user_id = (select auth.user_id())));--> statement-breakpoint
ALTER POLICY "messages_insert" ON "messages" TO "authenticated" WITH CHECK ("messages"."sender_id" = (select auth.user_id()) and exists(select 1 from conversation_members_rls where conversation_members_rls.conversation_id = "messages"."conversation_id" and conversation_members_rls.user_id = (select auth.user_id())));